#ifndef NPGR_DENSE_LEARNING_RULE_FACTORY_H
#define NPGR_DENSE_LEARNING_RULE_FACTORY_H

#include "dense_subnetwork/learning/DenseLearningModelSpec.h"
#include "source_file_realtime_v1_async/Network/inc/NetworkConstructStructure.h"

#include <list>
#include <memory>
#include <string>
#include <vector>

namespace npgr {

struct DenseLearningRuleInfo {
    // True when a legacy rule is supported by a registered dense learning
    // model. Unsupported entries remain in the table so legacy rule ids stay
    // stable, but dense synapses cannot bind to them.
    bool supported = false;
    // Registered dense learning model id. This is metadata only; model-specific
    // parameters live in DenseLearningRuleFieldTable.
    int factory_model_id = -1;
    // Original legacy rule name, kept for diagnostics.
    std::string rule_name;
    // Hook mask compiled from the model. Runtime arrays copy this per synapse
    // so pre/post/trigger kernels can skip unsupported phases cheaply.
    unsigned char flags = 0;
};

class IDenseLearningRuleModel;

enum DenseLearningModelIds {
    kDenseLearningUnknownModelId = -1,
#define NPGR_DENSE_LEARNING_MODEL(symbol, id, host_class, pre_fn, post_fn, trigger_fn) \
    symbol = id,
#include "dense_subnetwork/learning/DenseLearningModelList.inc"
#undef NPGR_DENSE_LEARNING_MODEL
};

enum DenseLearningConnectionRole : unsigned char {
    kDenseLearningConnectionNone = 0,
    kDenseLearningConnectionPlastic = 1u << 0,
    kDenseLearningConnectionTrigger = 1u << 1,
};

enum DenseLearningFlags : unsigned char {
    kDenseLearningUsesPre = 1u << 0,
    kDenseLearningUsesPost = 1u << 1,
    kDenseLearningUsesTrigger = 1u << 2,
    kDenseLearningUsesTriggerRouting = 1u << 3,
    kDenseLearningUsesKernelTable = 1u << 4,
};

// Host-side registry and compiler for dense learning rules. Concrete learning
// models are registered here; build/runtime paths consume only the generic
// flat tables generated by this factory.
class DenseLearningRuleFactory {
public:
    static DenseLearningRuleFactory& Instance();

    // Legacy rule ids are stable indices into the original LearningRule list.
    // A rule id is accepted only when it points to a supported table entry.
    bool IsSupportedLegacyRuleId(int legacy_rule_id) const;
    unsigned char FlagsForLegacyRuleId(int legacy_rule_id) const;
    const IDenseLearningRuleModel* FindByLegacyName(const std::string& name) const;
    const IDenseLearningRuleModel* FindByModelId(int factory_model_id) const;
    DenseLearningRuleInfo DescribeLegacyRule(int legacy_rule_id,
                                             const std::vector<DenseLearningRuleInfo>& table) const;
    // Build rule metadata plus rule-indexed parameter fields from the legacy
    // LearningRuleDescription list. The resulting rule ids remain identical to
    // the legacy list indices.
    bool BuildLegacyRuleTable(const std::list<LearningRuleDescription>& learning_rule_list,
                              std::vector<DenseLearningRuleInfo>* rule_table,
                              DenseLearningRuleFieldTable* rule_fields,
                              std::string* reason = nullptr) const;
    // Build a synapse-indexed runtime field table for the supplied registered
    // model specs. The table is still host-side here; GpuPropagationRuntime
    // uploads it after finalization.
    bool BuildFieldTable(const std::vector<DenseLearningModelSpec>& specs,
                         int synapse_count,
                         DenseLearningHostFieldTable* fields,
                         DenseLearningModelFieldIndexTable* indices,
                         std::string* reason = nullptr) const;
    // Convenience entry used by the dense runtime: include every registered
    // learning model so model ids can directly index the span table.
    bool BuildRegisteredFieldTable(int synapse_count,
                                   DenseLearningHostFieldTable* fields,
                                   DenseLearningModelFieldIndexTable* indices,
                                   std::string* reason = nullptr) const;
    // Compile per-synapse model ids and hook flags from plastic/trigger rule
    // ids. This produces runtime metadata but does not materialize parameters.
    bool CompileSynapseLearningBindings(int synapse_count,
                                        const std::vector<int>& plastic_rule_ids,
                                        const std::vector<int>& trigger_rule_ids,
                                        const std::vector<DenseLearningRuleInfo>& rule_table,
                                        std::vector<int>* plastic_model_ids,
                                        std::vector<unsigned char>* plastic_flags,
                                        std::vector<int>* trigger_model_ids,
                                        std::vector<unsigned char>* trigger_flags,
                                        std::string* reason = nullptr) const;
    // Expand rule-indexed parameters into synapse-indexed runtime fields for
    // the GPU kernels. Concrete models own the expansion policy.
    bool PopulateFieldTableFromRuleBindings(int synapse_count,
                                            const std::vector<int>& plastic_rule_ids,
                                            const std::vector<int>& plastic_model_ids,
                                            const std::vector<int>& trigger_rule_ids,
                                            const std::vector<int>& trigger_model_ids,
                                            const std::vector<float>& max_weights,
                                            const std::vector<DenseLearningRuleInfo>& rule_table,
                                            const DenseLearningRuleFieldTable& rule_fields,
                                            DenseLearningHostFieldTable* fields,
                                            std::string* reason = nullptr) const;
    // Query model-owned buffered activity requirements. The dense finalizer
    // uses this to size GPU learning spike rings without knowing which model
    // actually needs the buffer.
    float MaxBufferedTimeForRule(int legacy_rule_id,
                                 const std::vector<DenseLearningRuleInfo>& rule_table,
                                 const DenseLearningRuleFieldTable& rule_fields) const;
    float MaxBufferedTimeForBinding(int legacy_rule_id,
                                    int factory_model_id,
                                    const std::vector<DenseLearningRuleInfo>& rule_table,
                                    const DenseLearningRuleFieldTable& rule_fields) const;
    // Runs host-side metadata checks for every registered rule model. It is
    // called during dense build/init so extension mistakes fail before kernels.
    bool ValidateRegisteredModels(std::string* reason = nullptr) const;

private:
    DenseLearningRuleFactory();
    void Register(std::unique_ptr<IDenseLearningRuleModel> model);

    std::vector<std::unique_ptr<IDenseLearningRuleModel> > models_;
};

}  // namespace npgr

#endif
