"""C++ static-layout emission for generated legacy CPU neuron models."""

from __future__ import annotations

from pathlib import Path

from .model_ir import CompiledNeuronSpec


def emit_descriptor_header(model: CompiledNeuronSpec, differential_state_count: int | None = None) -> str:
    """Emit the descriptor fragment consumed by one generated concrete class."""
    differential_count = len(model.odes) if differential_state_count is None else differential_state_count
    guard = "NPGR_GENERATED_" + "".join(
        character if character.isalnum() else "_" for character in model.implementation_name.upper()
    ) + "_DESCRIPTOR_H"
    bindings = []
    for binding in model.input_bindings:
        bindings.append(
            "    {"
            f"{binding.connection_type}, {binding.state_slot}, 1.0f, "
            f"npgr::CustomInputDelivery::{binding.delivery}"
            "},"
        )
    binding_text = "\n".join(bindings) if bindings else "    {0, 0, 0.0f, npgr::CustomInputDelivery::AddToState},"
    return f"""// Generated by tools.model_codegen; do not edit.
#ifndef {guard}
#define {guard}

#include \"../source_file_realtime_v1_async/NeuralModel/inc/Custom/CustomEquationDescriptor.h\"

namespace npgr_generated {{

inline constexpr npgr::CustomInputBinding k{model.implementation_name}Inputs[] = {{
{binding_text}
}};

inline constexpr npgr::CustomEquationDescriptor k{model.implementation_name}Descriptor = {{
    \"{model.implementation_name}\",
    {len(model.state_names)},
    {differential_count},
    {model.voltage_slot},
    k{model.implementation_name}Inputs,
    {len(model.input_bindings)},
}};

}}  // namespace npgr_generated

#endif
"""


def write_descriptor_header(include_root: Path, model: CompiledNeuronSpec) -> Path:
    """Write one deterministic build-tree-only descriptor header."""
    output = include_root / "neuronbridge_codegen" / f"{model.implementation_name}Descriptor.h"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_descriptor_header(model), encoding="utf-8", newline="\n")
    return output
